name: CII Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the workflow'
        required: true
        default: 'Hello, World!'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Just run command
        run: echo "Hello, World! this is the second workflow"