name: My first workflow
on:
  push:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on:  ubuntu-22.04
    steps:
      - name: OS info
        run: echo "$(cat /etc/os-release)"

      - name: Just say hello
        run: echo "This is my firstworkflow"

